# Generated by Django 5.0.6 on 2024-09-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_statistic", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-id"]},
        ),
    ]
