# Generated by Django 5.0.6 on 2024-09-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_statistic", "0002_alter_payment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.BigIntegerField(),
        ),
    ]
