# Generated by Django 5.0.6 on 2024-09-20 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_statistic", "0003_alter_payment_payment_date_alter_product_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
