# Generated by Django 5.0.6 on 2024-10-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_statistic", "0004_alter_payment_payment_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="images",
        ),
    ]
