# Generated by Django 5.0.6 on 2024-10-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_statistic", "0005_rename_image_product_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="images",
            new_name="image",
        ),
    ]
